
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package es.valencia.services.nie.comunicaciones.v20;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-05-02T11:41:07.963+02:00
 * Generated source version: 2.7.18
 *
 */

@javax.jws.WebService(
                      serviceName = "ComunicacionesService",
                      portName = "ComunicacionesSOAP11",
                      targetNamespace = "http://www.valencia.es/services/nie/Comunicaciones/v20",
                      wsdlLocation = "http://prebus.valencia.es:7011/sbresource?WSDL/NotasInterioresElectronicas-pruebas/Servicios/Comunicaciones/Proveedores/Comunicaciones_v2.0_concreto",
                      endpointInterface = "es.valencia.services.nie.comunicaciones.v20.ComunicacionesPortType")

public class ComunicacionesPortTypeImpl implements ComunicacionesPortType {

    private static final Logger LOG = Logger.getLogger(ComunicacionesPortTypeImpl.class.getName());

    /* (non-Javadoc)
     * @see es.valencia.services.nie.comunicaciones.v20.ComunicacionesPortType#deleteComunicacion(es.valencia.services.nie.comunicaciones.CodigoComunicacionRequestTypeV10  request )*
     */
    @Override
	public es.valencia.services.nie.comunicaciones.CodigoComunicacionResponseTypeV10 deleteComunicacion(es.valencia.services.nie.comunicaciones.CodigoComunicacionRequestTypeV10 request) throws EstadoIncorrectoComunicacionPostconditionFault    {
        LOG.info("Executing operation deleteComunicacion");
        System.out.println(request);
        try {
            es.valencia.services.nie.comunicaciones.CodigoComunicacionResponseTypeV10 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new EstadoIncorrectoComunicacionPostconditionFault("EstadoIncorrectoComunicacionPostconditionFault...");
    }

    /* (non-Javadoc)
     * @see es.valencia.services.nie.comunicaciones.v20.ComunicacionesPortType#getComunicacion(es.valencia.services.nie.comunicaciones.GetComunicacionRequestTypeV10  request )*
     */
    @Override
	public es.valencia.services.nie.comunicaciones.ComunicacionResponseTypeV12 getComunicacion(es.valencia.services.nie.comunicaciones.GetComunicacionRequestTypeV10 request) throws ComunicacionPreconditionFault    {
        LOG.info("Executing operation getComunicacion");
        System.out.println(request);
        try {
            es.valencia.services.nie.comunicaciones.ComunicacionResponseTypeV12 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ComunicacionPreconditionFault("ComunicacionPreconditionFault...");
    }

    /* (non-Javadoc)
     * @see es.valencia.services.nie.comunicaciones.v20.ComunicacionesPortType#toFirmada(es.valencia.services.nie.comunicaciones.ToFirmadaRequestTypeV10  request )*
     */
    @Override
	public es.valencia.services.nie.comunicaciones.ComunicacionResponseTypeV12 toFirmada(es.valencia.services.nie.comunicaciones.ToFirmadaRequestTypeV10 request) throws ComunicacionPreconditionFault    {
        LOG.info("Executing operation toFirmada");
        System.out.println(request);
        try {
            es.valencia.services.nie.comunicaciones.ComunicacionResponseTypeV12 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ComunicacionPreconditionFault("ComunicacionPreconditionFault...");
    }

    /* (non-Javadoc)
     * @see es.valencia.services.nie.comunicaciones.v20.ComunicacionesPortType#addOrUpdateListaDestino(es.valencia.services.nie.comunicaciones.AddOrUpdateListaDestinoRequestTypeV10  request )*
     */
    @Override
	public es.valencia.services.nie.comunicaciones.ListaDestinoResponseTypeV11 addOrUpdateListaDestino(es.valencia.services.nie.comunicaciones.AddOrUpdateListaDestinoRequestTypeV10 request) throws UidNoExistePreconditionFault    {
        LOG.info("Executing operation addOrUpdateListaDestino");
        System.out.println(request);
        try {
            es.valencia.services.nie.comunicaciones.ListaDestinoResponseTypeV11 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new UidNoExistePreconditionFault("UidNoExistePreconditionFault...");
    }

    /* (non-Javadoc)
     * @see es.valencia.services.nie.comunicaciones.v20.ComunicacionesPortType#createOrUpdateComunicacion(es.valencia.services.nie.comunicaciones.CreateOrUpdateComunicacionRequestTypeV10  request )*
     */
    @Override
	public es.valencia.services.nie.comunicaciones.ComunicacionResponseTypeV12 createOrUpdateComunicacion(es.valencia.services.nie.comunicaciones.CreateOrUpdateComunicacionRequestTypeV10 request) throws ComunicacionPreconditionFault    {
        LOG.info("Executing operation createOrUpdateComunicacion");
        System.out.println(request);
        try {
            es.valencia.services.nie.comunicaciones.ComunicacionResponseTypeV12 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ComunicacionPreconditionFault("ComunicacionPreconditionFault...");
    }

    /* (non-Javadoc)
     * @see es.valencia.services.nie.comunicaciones.v20.ComunicacionesPortType#findListasUO(es.valencia.services.nie.comunicaciones.FindListasUORequestTypeV10  request )*
     */
    @Override
	public es.valencia.services.nie.comunicaciones.FindListasUOResponseTypeV10 findListasUO(es.valencia.services.nie.comunicaciones.FindListasUORequestTypeV10 request) throws UidNoExistePreconditionFault    {
        LOG.info("Executing operation findListasUO");
        System.out.println(request);
        try {
            es.valencia.services.nie.comunicaciones.FindListasUOResponseTypeV10 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new UidNoExistePreconditionFault("UidNoExistePreconditionFault...");
    }

    /* (non-Javadoc)
     * @see es.valencia.services.nie.comunicaciones.v20.ComunicacionesPortType#findListasDestino(es.valencia.services.nie.comunicaciones.FindListasDestinoRequestTypeV10  request )*
     */
    @Override
	public es.valencia.services.nie.comunicaciones.FindListasDestinoResponseTypeV11 findListasDestino(es.valencia.services.nie.comunicaciones.FindListasDestinoRequestTypeV10 request) throws UidNoExistePreconditionFault    {
        LOG.info("Executing operation findListasDestino");
        System.out.println(request);
        try {
            es.valencia.services.nie.comunicaciones.FindListasDestinoResponseTypeV11 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new UidNoExistePreconditionFault("UidNoExistePreconditionFault...");
    }

    /* (non-Javadoc)
     * @see es.valencia.services.nie.comunicaciones.v20.ComunicacionesPortType#toEnRedaccion(es.valencia.services.nie.comunicaciones.CodigoComunicacionRequestTypeV10  request )*
     */
    @Override
	public es.valencia.services.nie.comunicaciones.ComunicacionResponseTypeV12 toEnRedaccion(es.valencia.services.nie.comunicaciones.CodigoComunicacionRequestTypeV10 request) throws ComunicacionPreconditionFault    {
        LOG.info("Executing operation toEnRedaccion");
        System.out.println(request);
        try {
            es.valencia.services.nie.comunicaciones.ComunicacionResponseTypeV12 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ComunicacionPreconditionFault("ComunicacionPreconditionFault...");
    }

    /* (non-Javadoc)
     * @see es.valencia.services.nie.comunicaciones.v20.ComunicacionesPortType#getNI(es.valencia.services.nie.comunicaciones.GetNIRequestTypeV10  request )*
     */
    @Override
	public es.valencia.services.nie.comunicaciones.ComunicacionResponseTypeV12 getNI(es.valencia.services.nie.comunicaciones.GetNIRequestTypeV10 request) throws ComunicacionPreconditionFault    {
        LOG.info("Executing operation getNI");
        System.out.println(request);
        try {
            es.valencia.services.nie.comunicaciones.ComunicacionResponseTypeV12 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ComunicacionPreconditionFault("ComunicacionPreconditionFault...");
    }

    /* (non-Javadoc)
     * @see es.valencia.services.nie.comunicaciones.v20.ComunicacionesPortType#toRechazada(es.valencia.services.nie.comunicaciones.ToRechazadaRequestTypeV10  request )*
     */
    @Override
	public es.valencia.services.nie.comunicaciones.ComunicacionResponseTypeV12 toRechazada(es.valencia.services.nie.comunicaciones.ToRechazadaRequestTypeV10 request) throws ComunicacionPreconditionFault    {
        LOG.info("Executing operation toRechazada");
        System.out.println(request);
        try {
            es.valencia.services.nie.comunicaciones.ComunicacionResponseTypeV12 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ComunicacionPreconditionFault("ComunicacionPreconditionFault...");
    }

    /* (non-Javadoc)
     * @see es.valencia.services.nie.comunicaciones.v20.ComunicacionesPortType#toRedactada(es.valencia.services.nie.comunicaciones.CodigoComunicacionRequestTypeV10  request )*
     */
    @Override
	public es.valencia.services.nie.comunicaciones.ToRedactadaResponseTypeV12 toRedactada(es.valencia.services.nie.comunicaciones.CodigoComunicacionRequestTypeV10 request) throws ComunicacionPreconditionFault , ComunicacionPostconditionFault    {
        LOG.info("Executing operation toRedactada");
        System.out.println(request);
        try {
            es.valencia.services.nie.comunicaciones.ToRedactadaResponseTypeV12 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ComunicacionPreconditionFault("ComunicacionPreconditionFault...");
        //throw new ComunicacionPostconditionFault("ComunicacionPostconditionFault...");
    }

    /* (non-Javadoc)
     * @see es.valencia.services.nie.comunicaciones.v20.ComunicacionesPortType#deleteListaDestino(es.valencia.services.nie.comunicaciones.ListaDestinoRequestTypeV10  request )*
     */
    @Override
	public es.valencia.services.nie.comunicaciones.DeleteListaDestinoResponseTypeV10 deleteListaDestino(es.valencia.services.nie.comunicaciones.ListaDestinoRequestTypeV10 request) throws ListaReferenciadaPostconditionFault    {
        LOG.info("Executing operation deleteListaDestino");
        System.out.println(request);
        try {
            es.valencia.services.nie.comunicaciones.DeleteListaDestinoResponseTypeV10 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ListaReferenciadaPostconditionFault("ListaReferenciadaPostconditionFault...");
    }

    /* (non-Javadoc)
     * @see es.valencia.services.nie.comunicaciones.v20.ComunicacionesPortType#toFalloEnFirma(es.valencia.services.nie.comunicaciones.ToFalloEnFirmaRequestTypeV10  request )*
     */
    @Override
	public es.valencia.services.nie.comunicaciones.ComunicacionResponseTypeV12 toFalloEnFirma(es.valencia.services.nie.comunicaciones.ToFalloEnFirmaRequestTypeV10 request) throws ComunicacionPreconditionFault    {
        LOG.info("Executing operation toFalloEnFirma");
        System.out.println(request);
        try {
            es.valencia.services.nie.comunicaciones.ComunicacionResponseTypeV12 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ComunicacionPreconditionFault("ComunicacionPreconditionFault...");
    }

    /* (non-Javadoc)
     * @see es.valencia.services.nie.comunicaciones.v20.ComunicacionesPortType#addOrUpdateAdjunto(es.valencia.services.nie.comunicaciones.AddOrUpdateAdjuntoRequestTypeV10  request )*
     */
    @Override
	public es.valencia.services.nie.comunicaciones.ComunicacionResponseTypeV12 addOrUpdateAdjunto(es.valencia.services.nie.comunicaciones.AddOrUpdateAdjuntoRequestTypeV10 request) throws ComunicacionPreconditionFault    {
        LOG.info("Executing operation addOrUpdateAdjunto");
        System.out.println(request);
        try {
            es.valencia.services.nie.comunicaciones.ComunicacionResponseTypeV12 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ComunicacionPreconditionFault("ComunicacionPreconditionFault...");
    }

    /* (non-Javadoc)
     * @see es.valencia.services.nie.comunicaciones.v20.ComunicacionesPortType#updateNI(es.valencia.services.nie.comunicaciones.UpdateNIRequestTypeV10  request )*
     */
    @Override
	public es.valencia.services.nie.comunicaciones.UpdateNIResponseTypeV10 updateNI(es.valencia.services.nie.comunicaciones.UpdateNIRequestTypeV10 request) throws ComunicacionPreconditionFault    {
        LOG.info("Executing operation updateNI");
        System.out.println(request);
        try {
            es.valencia.services.nie.comunicaciones.UpdateNIResponseTypeV10 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ComunicacionPreconditionFault("ComunicacionPreconditionFault...");
    }

    /* (non-Javadoc)
     * @see es.valencia.services.nie.comunicaciones.v20.ComunicacionesPortType#updateMiembrosListaDestino(es.valencia.services.nie.comunicaciones.UpdateMiembrosListaDestinoRequestTypeV10  request )*
     */
    @Override
	public es.valencia.services.nie.comunicaciones.UpdateMiembrosListaDestinoResponseTypeV11 updateMiembrosListaDestino(es.valencia.services.nie.comunicaciones.UpdateMiembrosListaDestinoRequestTypeV10 request) throws UidNoExistePreconditionFault    {
        LOG.info("Executing operation updateMiembrosListaDestino");
        System.out.println(request);
        try {
            es.valencia.services.nie.comunicaciones.UpdateMiembrosListaDestinoResponseTypeV11 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new UidNoExistePreconditionFault("UidNoExistePreconditionFault...");
    }

    /* (non-Javadoc)
     * @see es.valencia.services.nie.comunicaciones.v20.ComunicacionesPortType#recepcionarNI(es.valencia.services.nie.comunicaciones.RecepcionarNIRequestTypeV10  request )*
     */
    @Override
	public es.valencia.services.nie.comunicaciones.NIResponseTypeV12 recepcionarNI(es.valencia.services.nie.comunicaciones.RecepcionarNIRequestTypeV10 request) throws ComunicacionPreconditionFault    {
        LOG.info("Executing operation recepcionarNI");
        System.out.println(request);
        try {
            es.valencia.services.nie.comunicaciones.NIResponseTypeV12 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ComunicacionPreconditionFault("ComunicacionPreconditionFault...");
    }

    /* (non-Javadoc)
     * @see es.valencia.services.nie.comunicaciones.v20.ComunicacionesPortType#findComunicaciones(es.valencia.services.nie.comunicaciones.FindComunicacionesRequestTypeV10  request )*
     */
    @Override
	public es.valencia.services.nie.comunicaciones.FindComunicacionesResponseTypeV11 findComunicaciones(es.valencia.services.nie.comunicaciones.FindComunicacionesRequestTypeV10 request) {
        LOG.info("Executing operation findComunicaciones");
        System.out.println(request);
        try {
            es.valencia.services.nie.comunicaciones.FindComunicacionesResponseTypeV11 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see es.valencia.services.nie.comunicaciones.v20.ComunicacionesPortType#toCancelada(es.valencia.services.nie.comunicaciones.ToCanceladaRequestTypeV10  request )*
     */
    @Override
	public es.valencia.services.nie.comunicaciones.ComunicacionResponseTypeV12 toCancelada(es.valencia.services.nie.comunicaciones.ToCanceladaRequestTypeV10 request) throws ComunicacionPreconditionFault    {
        LOG.info("Executing operation toCancelada");
        System.out.println(request);
        try {
            es.valencia.services.nie.comunicaciones.ComunicacionResponseTypeV12 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ComunicacionPreconditionFault("ComunicacionPreconditionFault...");
    }

    /* (non-Javadoc)
     * @see es.valencia.services.nie.comunicaciones.v20.ComunicacionesPortType#removeAdjunto(es.valencia.services.nie.comunicaciones.RemoveAdjuntoRequestTypeV10  request )*
     */
    @Override
	public es.valencia.services.nie.comunicaciones.RemoveAdjuntoResponseTypeV12 removeAdjunto(es.valencia.services.nie.comunicaciones.RemoveAdjuntoRequestTypeV10 request) throws ComunicacionPreconditionFault    {
        LOG.info("Executing operation removeAdjunto");
        System.out.println(request);
        try {
            es.valencia.services.nie.comunicaciones.RemoveAdjuntoResponseTypeV12 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ComunicacionPreconditionFault("ComunicacionPreconditionFault...");
    }

    /* (non-Javadoc)
     * @see es.valencia.services.nie.comunicaciones.v20.ComunicacionesPortType#getListaDestino(es.valencia.services.nie.comunicaciones.ListaDestinoRequestTypeV10  request )*
     */
    @Override
	public es.valencia.services.nie.comunicaciones.ListaDestinoResponseTypeV11 getListaDestino(es.valencia.services.nie.comunicaciones.ListaDestinoRequestTypeV10 request) throws UidNoExistePreconditionFault    {
        LOG.info("Executing operation getListaDestino");
        System.out.println(request);
        try {
            es.valencia.services.nie.comunicaciones.ListaDestinoResponseTypeV11 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new UidNoExistePreconditionFault("UidNoExistePreconditionFault...");
    }

    /* (non-Javadoc)
     * @see es.valencia.services.nie.comunicaciones.v20.ComunicacionesPortType#toPendienteFirma(es.valencia.services.nie.comunicaciones.CodigoComunicacionRequestTypeV10  request )*
     */
    @Override
	public es.valencia.services.nie.comunicaciones.ComunicacionResponseTypeV12 toPendienteFirma(es.valencia.services.nie.comunicaciones.CodigoComunicacionRequestTypeV10 request) throws ComunicacionPreconditionFault    {
        LOG.info("Executing operation toPendienteFirma");
        System.out.println(request);
        try {
            es.valencia.services.nie.comunicaciones.ComunicacionResponseTypeV12 _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new ComunicacionPreconditionFault("ComunicacionPreconditionFault...");
    }

}
