
package es.valencia.services.nie.comunicaciones.v20;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-05-02T11:41:07.899+02:00
 * Generated source version: 2.7.18
 */

@WebFault(name = "EstadoIncorrectoComunicacionPostconditionFault", targetNamespace = "http://www.valencia.es/services/nie/Comunicaciones/v20")
public class EstadoIncorrectoComunicacionPostconditionFault extends Exception {

	private static final long serialVersionUID = 8210878987376904790L;

	private es.valencia.services.nie.comunicaciones.EstadoIncorrectoComunicacionPostconditionFaultMessageTypeV10 estadoIncorrectoComunicacionPostconditionFault;

    public EstadoIncorrectoComunicacionPostconditionFault() {
        super();
    }

    public EstadoIncorrectoComunicacionPostconditionFault(String message) {
        super(message);
    }

    public EstadoIncorrectoComunicacionPostconditionFault(String message, Throwable cause) {
        super(message, cause);
    }

    public EstadoIncorrectoComunicacionPostconditionFault(String message, es.valencia.services.nie.comunicaciones.EstadoIncorrectoComunicacionPostconditionFaultMessageTypeV10 estadoIncorrectoComunicacionPostconditionFault) {
        super(message);
        this.estadoIncorrectoComunicacionPostconditionFault = estadoIncorrectoComunicacionPostconditionFault;
    }

    public EstadoIncorrectoComunicacionPostconditionFault(String message, es.valencia.services.nie.comunicaciones.EstadoIncorrectoComunicacionPostconditionFaultMessageTypeV10 estadoIncorrectoComunicacionPostconditionFault, Throwable cause) {
        super(message, cause);
        this.estadoIncorrectoComunicacionPostconditionFault = estadoIncorrectoComunicacionPostconditionFault;
    }

    public es.valencia.services.nie.comunicaciones.EstadoIncorrectoComunicacionPostconditionFaultMessageTypeV10 getFaultInfo() {
        return estadoIncorrectoComunicacionPostconditionFault;
    }
}
