
package es.valencia.services.nie.comunicaciones.v20;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-05-02T11:41:07.955+02:00
 * Generated source version: 2.7.18
 */

@WebFault(name = "ListaReferenciadaPostconditionFault", targetNamespace = "http://www.valencia.es/services/nie/Comunicaciones/v20")
public class ListaReferenciadaPostconditionFault extends Exception {

	private static final long serialVersionUID = -8712571596628462424L;

	private es.valencia.services.nie.comunicaciones.ListaReferenciadaPostconditionFaultMessageTypeV10 listaReferenciadaPostconditionFault;

    public ListaReferenciadaPostconditionFault() {
        super();
    }

    public ListaReferenciadaPostconditionFault(String message) {
        super(message);
    }

    public ListaReferenciadaPostconditionFault(String message, Throwable cause) {
        super(message, cause);
    }

    public ListaReferenciadaPostconditionFault(String message, es.valencia.services.nie.comunicaciones.ListaReferenciadaPostconditionFaultMessageTypeV10 listaReferenciadaPostconditionFault) {
        super(message);
        this.listaReferenciadaPostconditionFault = listaReferenciadaPostconditionFault;
    }

    public ListaReferenciadaPostconditionFault(String message, es.valencia.services.nie.comunicaciones.ListaReferenciadaPostconditionFaultMessageTypeV10 listaReferenciadaPostconditionFault, Throwable cause) {
        super(message, cause);
        this.listaReferenciadaPostconditionFault = listaReferenciadaPostconditionFault;
    }

    public es.valencia.services.nie.comunicaciones.ListaReferenciadaPostconditionFaultMessageTypeV10 getFaultInfo() {
        return listaReferenciadaPostconditionFault;
    }
}
