package es.valencia.services.nie.unidadesorganizativas.v20;

import javax.xml.ws.WebFault;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-05-02T11:41:09.237+02:00
 * Generated source version: 2.7.18
 */

@WebFault(name = "UnidadPreconditionFault", targetNamespace = "http://www.valencia.es/services/nie/UnidadesOrganizativas/v20")
public class UnidadPreconditionFault extends Exception {

	private static final long serialVersionUID = 3987370557080251316L;

	private es.valencia.services.nie.unidadesorganizativas.UnidadPreconditionFaultTypeV10 unidadPreconditionFault;

	public UnidadPreconditionFault() {

		super();
	}

	public UnidadPreconditionFault(String message) {

		super(message);
	}

	public UnidadPreconditionFault(String message, Throwable cause) {

		super(message, cause);
	}

	public UnidadPreconditionFault(String message,
			es.valencia.services.nie.unidadesorganizativas.UnidadPreconditionFaultTypeV10 unidadPreconditionFault) {

		super(message);
		this.unidadPreconditionFault = unidadPreconditionFault;
	}

	public UnidadPreconditionFault(String message,
			es.valencia.services.nie.unidadesorganizativas.UnidadPreconditionFaultTypeV10 unidadPreconditionFault,
			Throwable cause) {

		super(message, cause);
		this.unidadPreconditionFault = unidadPreconditionFault;
	}

	public es.valencia.services.nie.unidadesorganizativas.UnidadPreconditionFaultTypeV10 getFaultInfo() {

		return unidadPreconditionFault;
	}
}
