/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package es.valencia.services.nie.unidadesorganizativas.v20;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-05-02T11:41:09.259+02:00
 * Generated source version: 2.7.18
 *
 */

@javax.jws.WebService(serviceName = "UnidadesOrganizativasService", portName = "UnidadesOrganizativasSOAP11", targetNamespace = "http://www.valencia.es/services/nie/UnidadesOrganizativas/v20", wsdlLocation = "http://prebus.valencia.es:7011/sbresource?WSDL/NotasInterioresElectronicas-pruebas/Servicios/Comunicaciones/Proveedores/UnidadesOrganizativas_v2.0_concreto", endpointInterface = "es.valencia.services.nie.unidadesorganizativas.v20.UnidadesOrganizativasPortType")
public class UnidadesOrganizativasPortTypeImpl implements UnidadesOrganizativasPortType {

	private static final Logger LOG = Logger.getLogger(UnidadesOrganizativasPortTypeImpl.class.getName());

	/*
	 * (non-Javadoc)
	 *
	 * @see es.valencia.services.nie.unidadesorganizativas.v20.UnidadesOrganizativasPortType#
	 * addOrUpdateUnidad
	 * (es.valencia.services.nie.unidadesorganizativas.AddOrUpdateUnidadRequestTypeV20 request )*
	 */
	@Override
	public es.valencia.services.nie.unidadesorganizativas.UnidadResponseTypeV20 addOrUpdateUnidad(
			es.valencia.services.nie.unidadesorganizativas.AddOrUpdateUnidadRequestTypeV20 request)
			throws UnidadPreconditionFault {

		LOG.info("Executing operation addOrUpdateUnidad");
		System.out.println(request);
		try {
			es.valencia.services.nie.unidadesorganizativas.UnidadResponseTypeV20 _return = null;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new UnidadPreconditionFault("UnidadPreconditionFault...");
	}

	/*
	 * (non-Javadoc)
	 *
	 * @see
	 * es.valencia.services.nie.unidadesorganizativas.v20.UnidadesOrganizativasPortType#removeUnidad
	 * (es.valencia.services.nie.unidadesorganizativas.UidRequestTypeV10 request )*
	 */
	@Override
	public es.valencia.services.nie.unidadesorganizativas.RemoveUnidadResponseTypeV10 removeUnidad(
			es.valencia.services.nie.unidadesorganizativas.UidRequestTypeV10 request) {

		LOG.info("Executing operation removeUnidad");
		System.out.println(request);
		try {
			es.valencia.services.nie.unidadesorganizativas.RemoveUnidadResponseTypeV10 _return = null;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

	/*
	 * (non-Javadoc)
	 *
	 * @see
	 * es.valencia.services.nie.unidadesorganizativas.v20.UnidadesOrganizativasPortType#getUnidad
	 * (es.valencia.services.nie.unidadesorganizativas.UidRequestTypeV10 request )*
	 */
	@Override
	public es.valencia.services.nie.unidadesorganizativas.UnidadResponseTypeV20 getUnidad(
			es.valencia.services.nie.unidadesorganizativas.UidRequestTypeV10 request) throws UnidadPreconditionFault {

		LOG.info("Executing operation getUnidad");
		System.out.println(request);
		try {
			es.valencia.services.nie.unidadesorganizativas.UnidadResponseTypeV20 _return = null;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
		// throw new UnidadPreconditionFault("UnidadPreconditionFault...");
	}

	/*
	 * (non-Javadoc)
	 *
	 * @see
	 * es.valencia.services.nie.unidadesorganizativas.v20.UnidadesOrganizativasPortType#findUnidades
	 * (es.valencia.services.nie.unidadesorganizativas.FindUnidadesRequestTypeV12 request )*
	 */
	@Override
	public es.valencia.services.nie.unidadesorganizativas.FindUnidadesResponseTypeV20 findUnidades(
			es.valencia.services.nie.unidadesorganizativas.FindUnidadesRequestTypeV12 request) {

		LOG.info("Executing operation findUnidades");
		System.out.println(request);
		try {
			es.valencia.services.nie.unidadesorganizativas.FindUnidadesResponseTypeV20 _return = null;
			return _return;
		} catch (java.lang.Exception ex) {
			ex.printStackTrace();
			throw new RuntimeException(ex);
		}
	}

}
