package es.valencia.services.esb.comunicacioneselectronicas.v20;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-08-11T12:27:45.108+02:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://www.valencia.es/services/esb/ComunicacionesElectronicas/v20", name = "ComunicacionesElectronicasPortType")
@XmlSeeAlso({es.valencia.services.esb.comunicacioneselectronicas.ObjectFactory.class, es.valencia.schema.nie.unidadorganizativa.ObjectFactory.class, es.valencia.schema.authorization.ObjectFactory.class, es.valencia.schema.serticfaultmessage.ObjectFactory.class, ObjectFactory.class, es.valencia.schema.tiposbase.ObjectFactory.class, es.valencia.schema.serticentidadbase.ObjectFactory.class, es.valencia.schema.niedomain.comunicacion.ObjectFactory.class, es.valencia.schema.nie.listadestinos.ObjectFactory.class, es.valencia.schema.nie.common.ObjectFactory.class, es.valencia.schema.nie.comunicacion.ObjectFactory.class, es.valencia.services.niedomain.comunicaciones.ObjectFactory.class, es.valencia.services.nie.comunicaciones.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ComunicacionesElectronicasPortType {

    /**
     * Caso de uso 3.3.1: Generar Comunicación
     * 				Caso de
     * 				uso 3.3.2: Editar Comunicación
     * 			
     */
    @WebResult(name = "CreateOrUpdateComunicacionResponse", targetNamespace = "http://www.valencia.es/services/esb/ComunicacionesElectronicas/v20", partName = "response")
    @WebMethod(action = "http://www.valencia.es/services/esb/ComunicacionesElectronicas/v20/createOrUpdateComunicacion")
    public es.valencia.services.nie.comunicaciones.ComunicacionResponseTypeV12 createOrUpdateComunicacion(
        @WebParam(partName = "request", name = "CreateOrUpdateComunicacionRequest", targetNamespace = "http://www.valencia.es/services/esb/ComunicacionesElectronicas/v20")
        es.valencia.services.esb.comunicacioneselectronicas.CreateOrUpdateComunicacionRequestTypeV10 request
    ) throws ComunicacionPreconditionFault;

    /**
     * Caso de uso 3.3.3: Borrar Comunicación
     * 			
     */
    @WebResult(name = "DeleteComunicacionResponse", targetNamespace = "http://www.valencia.es/services/esb/ComunicacionesElectronicas/v20", partName = "response")
    @WebMethod(action = "http://www.valencia.es/services/esb/ComunicacionesElectronicas/v20/deleteComunicacion")
    public es.valencia.services.nie.comunicaciones.CodigoComunicacionResponseTypeV10 deleteComunicacion(
        @WebParam(partName = "request", name = "DeleteComunicacionRequest", targetNamespace = "http://www.valencia.es/services/esb/ComunicacionesElectronicas/v20")
        es.valencia.services.nie.comunicaciones.CodigoComunicacionRequestTypeV10 request
    ) throws EstadoIncorrectoComunicacionPostconditionFault;

    /**
     * 
     */
    @WebResult(name = "FindComunicacionesResponse", targetNamespace = "http://www.valencia.es/services/esb/ComunicacionesElectronicas/v20", partName = "response")
    @WebMethod(action = "http://www.valencia.es/services/esb/ComunicacionesElectronicas/v20/findComunicaciones")
    public es.valencia.services.nie.comunicaciones.FindComunicacionesResponseTypeV11 findComunicaciones(
        @WebParam(partName = "request", name = "FindComunicacionesRequest", targetNamespace = "http://www.valencia.es/services/esb/ComunicacionesElectronicas/v20")
        es.valencia.services.nie.comunicaciones.FindComunicacionesRequestTypeV10 request
    );

    /**
     * Caso de uso 3.3.2: Editar Comunicación
     * 			
     */
    @WebResult(name = "AddOrUpdateAdjuntoResponse", targetNamespace = "http://www.valencia.es/services/esb/ComunicacionesElectronicas/v20", partName = "response")
    @WebMethod(action = "http://www.valencia.es/services/esb/ComunicacionesElectronicas/v20/addOrUpdateAdjunto")
    public es.valencia.services.nie.comunicaciones.ComunicacionResponseTypeV12 addOrUpdateAdjunto(
        @WebParam(partName = "request", name = "AddOrUpdateAdjuntoRequest", targetNamespace = "http://www.valencia.es/services/esb/ComunicacionesElectronicas/v20")
        es.valencia.services.niedomain.comunicaciones.AddOrUpdateAdjuntoRequestTypeV10 request
    ) throws ComunicacionPreconditionFault;

    /**
     * Caso de uso 3.3.2: Editar Comunicación
     * 			
     */
    @WebResult(name = "RemoveAdjuntoResponse", targetNamespace = "http://www.valencia.es/services/esb/ComunicacionesElectronicas/v20", partName = "response")
    @WebMethod(action = "http://www.valencia.es/services/esb/ComunicacionesElectronicas/v20/removeAdjunto")
    public es.valencia.services.nie.comunicaciones.ComunicacionResponseTypeV12 removeAdjunto(
        @WebParam(partName = "request", name = "RemoveAdjuntoRequest", targetNamespace = "http://www.valencia.es/services/esb/ComunicacionesElectronicas/v20")
        es.valencia.services.nie.comunicaciones.RemoveAdjuntoRequestTypeV10 request
    ) throws ComunicacionPreconditionFault;

    @WebResult(name = "GetComunicacionResponse", targetNamespace = "http://www.valencia.es/services/esb/ComunicacionesElectronicas/v20", partName = "response")
    @WebMethod(action = "http://www.valencia.es/services/esb/ComunicacionesElectronicas/v20/getComunicacion")
    public es.valencia.services.niedomain.comunicaciones.ComunicacionResponseTypeV12 getComunicacion(
        @WebParam(partName = "request", name = "GetComunicacionRequest", targetNamespace = "http://www.valencia.es/services/esb/ComunicacionesElectronicas/v20")
        es.valencia.services.niedomain.comunicaciones.GetComunicacionRequestTypeV10 request
    ) throws ComunicacionPreconditionFault;

    /**
     * Caso de uso 3.3.4: Finalizar Comunicación
     * 			
     */
    @WebResult(name = "FinalizarComunicacionResponse", targetNamespace = "http://www.valencia.es/services/esb/ComunicacionesElectronicas/v20", partName = "response")
    @WebMethod(action = "http://www.valencia.es/services/esb/ComunicacionesElectronicas/v20/finalizarComunicacion")
    public es.valencia.services.niedomain.comunicaciones.ComunicacionResponseTypeV12 finalizarComunicacion(
        @WebParam(partName = "request", name = "FinalizarComunicacionRequest", targetNamespace = "http://www.valencia.es/services/esb/ComunicacionesElectronicas/v20")
        es.valencia.services.nie.comunicaciones.CodigoComunicacionRequestTypeV10 request
    ) throws ComunicacionPostconditionFault, ComunicacionPreconditionFault;

    @WebResult(name = "GetNIResponse", targetNamespace = "http://www.valencia.es/services/esb/ComunicacionesElectronicas/v20", partName = "response")
    @WebMethod(action = "http://www.valencia.es/services/esb/ComunicacionesElectronicas/v20/getNI")
    public es.valencia.services.niedomain.comunicaciones.ComunicacionResponseTypeV12 getNI(
        @WebParam(partName = "request", name = "GetNIRequest", targetNamespace = "http://www.valencia.es/services/esb/ComunicacionesElectronicas/v20")
        es.valencia.services.niedomain.comunicaciones.GetNIRequestTypeV10 request
    ) throws ComunicacionPreconditionFault;

    /**
     * 
     */
    @WebResult(name = "AportarAExpedienteResponse", targetNamespace = "http://www.valencia.es/services/esb/ComunicacionesElectronicas/v20", partName = "response")
    @WebMethod(action = "http://www.valencia.es/services/esb/ComunicacionesElectronicas/v20/aportarAExpediente")
    public es.valencia.services.esb.comunicacioneselectronicas.AportarAExpedienteResponseTypeV20 aportarAExpediente(
        @WebParam(partName = "response", name = "AportarAExpedienteRequest", targetNamespace = "http://www.valencia.es/services/esb/ComunicacionesElectronicas/v20")
        es.valencia.services.esb.comunicacioneselectronicas.AportarAExpedienteRequestTypeV20 response
    ) throws ComunicacionPreconditionFault;

    /**
     * Caso de USO 3.3.7: Cancelar Comunicación
     * 			
     */
    @WebResult(name = "CancelarComunicacionResponse", targetNamespace = "http://www.valencia.es/services/esb/ComunicacionesElectronicas/v20", partName = "response")
    @WebMethod(action = "http://www.valencia.es/services/esb/ComunicacionesElectronicas/v20/cancelarComunicacion")
    public es.valencia.services.niedomain.comunicaciones.ComunicacionResponseTypeV12 cancelarComunicacion(
        @WebParam(partName = "request", name = "CancelarComunicacionRequest", targetNamespace = "http://www.valencia.es/services/esb/ComunicacionesElectronicas/v20")
        es.valencia.services.niedomain.comunicaciones.CancelarComunicacionRequestTypeV10 request
    ) throws ComunicacionPreconditionFault;

    /**
     * Caso de USO 3.3.10: Cancelar Comunicación
     * 			
     */
    @WebResult(name = "RecepcionarNIResponse", targetNamespace = "http://www.valencia.es/services/esb/ComunicacionesElectronicas/v20", partName = "response")
    @WebMethod(action = "http://www.valencia.es/services/esb/ComunicacionesElectronicas/v20/recepcionarNI")
    public es.valencia.services.nie.comunicaciones.NIResponseTypeV12 recepcionarNI(
        @WebParam(partName = "request", name = "RecepcionarNIRequest", targetNamespace = "http://www.valencia.es/services/esb/ComunicacionesElectronicas/v20")
        es.valencia.services.nie.comunicaciones.RecepcionarNIRequestTypeV10 request
    ) throws ComunicacionPreconditionFault;

    /**
     * Caso de uso: 3.3.12 Redactar Comunicacion
     * 			
     */
    @WebResult(name = "ToEnRedaccionResponse", targetNamespace = "http://www.valencia.es/services/esb/ComunicacionesElectronicas/v20", partName = "response")
    @WebMethod(action = "http://www.valencia.es/services/esb/ComunicacionesElectronicas/v20/toEnRedaccion")
    public es.valencia.services.nie.comunicaciones.ComunicacionResponseTypeV12 toEnRedaccion(
        @WebParam(partName = "request", name = "ToEnRedaccionRequest", targetNamespace = "http://www.valencia.es/services/esb/ComunicacionesElectronicas/v20")
        es.valencia.services.nie.comunicaciones.CodigoComunicacionRequestTypeV10 request
    ) throws ComunicacionPreconditionFault;
}
