package es.valencia.services.esb.comunicacioneselectronicas.v20;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-08-11T12:27:45.119+02:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "ComunicacionesElectronicasService", 
                  wsdlLocation = "http://prebus.valencia.es:7011/sbresource?WSDL/NotasInterioresElectronicas-pruebas/Servicios/Comunicaciones/Publicados/ComunicacionesOSB_v2.0_concreto",
                  targetNamespace = "http://www.valencia.es/services/esb/ComunicacionesElectronicas/v20") 
public class ComunicacionesElectronicasService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.valencia.es/services/esb/ComunicacionesElectronicas/v20", "ComunicacionesElectronicasService");
    public final static QName ComunicacionesElectronicasSOAP11 = new QName("http://www.valencia.es/services/esb/ComunicacionesElectronicas/v20", "ComunicacionesElectronicasSOAP11");
    static {
        URL url = null;
        try {
            url = new URL("http://prebus.valencia.es:7011/sbresource?WSDL/NotasInterioresElectronicas-pruebas/Servicios/Comunicaciones/Publicados/ComunicacionesOSB_v2.0_concreto");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ComunicacionesElectronicasService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://prebus.valencia.es:7011/sbresource?WSDL/NotasInterioresElectronicas-pruebas/Servicios/Comunicaciones/Publicados/ComunicacionesOSB_v2.0_concreto");
        }
        WSDL_LOCATION = url;
    }

    public ComunicacionesElectronicasService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ComunicacionesElectronicasService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ComunicacionesElectronicasService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ComunicacionesElectronicasService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ComunicacionesElectronicasService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ComunicacionesElectronicasService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ComunicacionesElectronicasPortType
     */
    @WebEndpoint(name = "ComunicacionesElectronicasSOAP11")
    public ComunicacionesElectronicasPortType getComunicacionesElectronicasSOAP11() {
        return super.getPort(ComunicacionesElectronicasSOAP11, ComunicacionesElectronicasPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ComunicacionesElectronicasPortType
     */
    @WebEndpoint(name = "ComunicacionesElectronicasSOAP11")
    public ComunicacionesElectronicasPortType getComunicacionesElectronicasSOAP11(WebServiceFeature... features) {
        return super.getPort(ComunicacionesElectronicasSOAP11, ComunicacionesElectronicasPortType.class, features);
    }

}
