
package es.valencia.services.niedomain.unidadesorganizativas.v20;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-08-11T11:49:47.331+02:00
 * Generated source version: 2.7.18
 */

@WebFault(name = "UnidadPreconditionFault", targetNamespace = "http://www.valencia.es/services/nieDomain/UnidadesOrganizativas/v20")
public class UnidadPreconditionFault extends Exception {
    
	private static final long serialVersionUID = 8840883383069045582L;
	
	private es.valencia.services.nie.unidadesorganizativas.UnidadPreconditionFaultTypeV10 unidadPreconditionFault;

    public UnidadPreconditionFault() {
        super();
    }
    
    public UnidadPreconditionFault(String message) {
        super(message);
    }
    
    public UnidadPreconditionFault(String message, Throwable cause) {
        super(message, cause);
    }

    public UnidadPreconditionFault(String message, es.valencia.services.nie.unidadesorganizativas.UnidadPreconditionFaultTypeV10 unidadPreconditionFault) {
        super(message);
        this.unidadPreconditionFault = unidadPreconditionFault;
    }

    public UnidadPreconditionFault(String message, es.valencia.services.nie.unidadesorganizativas.UnidadPreconditionFaultTypeV10 unidadPreconditionFault, Throwable cause) {
        super(message, cause);
        this.unidadPreconditionFault = unidadPreconditionFault;
    }

    public es.valencia.services.nie.unidadesorganizativas.UnidadPreconditionFaultTypeV10 getFaultInfo() {
        return this.unidadPreconditionFault;
    }
}
