
package es.valencia.services.niedomain.unidadesorganizativas.v20;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-08-11T11:49:47.323+02:00
 * Generated source version: 2.7.18
 * 
 */
public final class UnidadesOrganizativasPortType_UnidadesOrganizativasSOAP11_Client {

    private static final QName SERVICE_NAME = new QName("http://www.valencia.es/services/nieDomain/UnidadesOrganizativas/v20", "UnidadesOrganizativasService");

    private UnidadesOrganizativasPortType_UnidadesOrganizativasSOAP11_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = UnidadesOrganizativasService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        UnidadesOrganizativasService ss = new UnidadesOrganizativasService(wsdlURL, SERVICE_NAME);
        UnidadesOrganizativasPortType port = ss.getUnidadesOrganizativasSOAP11();  
        
        {
        System.out.println("Invoking getUnidad...");
        es.valencia.services.niedomain.unidadesorganizativas.GetUnidadRequestTypeV12 _getUnidad_request = null;
        try {
            es.valencia.services.niedomain.unidadesorganizativas.UnidadResponseTypeV20 _getUnidad__return = port.getUnidad(_getUnidad_request);
            System.out.println("getUnidad.result=" + _getUnidad__return);

        } catch (UnidadPreconditionFault e) { 
            System.out.println("Expected exception: UnidadPreconditionFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking addOrUpdateUnidad...");
        es.valencia.services.niedomain.unidadesorganizativas.AddOrUpdateUnidadRequestTypeV20 _addOrUpdateUnidad_request = null;
        try {
            es.valencia.services.niedomain.unidadesorganizativas.UnidadResponseTypeV20 _addOrUpdateUnidad__return = port.addOrUpdateUnidad(_addOrUpdateUnidad_request);
            System.out.println("addOrUpdateUnidad.result=" + _addOrUpdateUnidad__return);

        } catch (UnidadPreconditionFault e) { 
            System.out.println("Expected exception: UnidadPreconditionFault has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
