package es.valencia.services.niedomain.unidadesorganizativas.v20;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-08-11T11:49:47.337+02:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://www.valencia.es/services/nieDomain/UnidadesOrganizativas/v20", name = "UnidadesOrganizativasPortType")
@XmlSeeAlso({es.valencia.schema.niedomain.unidadorganizativa.ObjectFactory.class, es.valencia.schema.nie.unidadorganizativa.ObjectFactory.class, es.valencia.schema.authorization.ObjectFactory.class, es.valencia.schema.serticfaultmessage.ObjectFactory.class, es.valencia.services.niedomain.unidadesorganizativas.ObjectFactory.class, es.valencia.services.nie.unidadesorganizativas.ObjectFactory.class, es.valencia.schema.tiposbase.ObjectFactory.class, ObjectFactory.class, es.valencia.schema.serticentidadbase.ObjectFactory.class, es.valencia.schema.nie.common.ObjectFactory.class, es.valencia.schema.headers.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface UnidadesOrganizativasPortType {

    /**
     * Precondiciones:
     * 				- El uid de la unidad debe existir
     * 			
     */
    @WebResult(name = "GetUnidadResponse", targetNamespace = "http://www.valencia.es/services/nieDomain/UnidadesOrganizativas/v20", partName = "response")
    @WebMethod(action = "http://www.valencia.es/services/nieDomain/UnidadesOrganizativas/v10/getUnidad")
    public es.valencia.services.niedomain.unidadesorganizativas.UnidadResponseTypeV20 getUnidad(
        @WebParam(partName = "request", name = "GetUnidadRequest", targetNamespace = "http://www.valencia.es/services/nieDomain/UnidadesOrganizativas/v20")
        es.valencia.services.niedomain.unidadesorganizativas.GetUnidadRequestTypeV12 request
    ) throws UnidadPreconditionFault;

    /**
     * Precondiciones:
     * 				- El uid de la unidad padre debe existir
     * 				- La unidad padre debe estar vigente
     * 			
     */
    @WebResult(name = "AddOrUpdateUnidadResponse", targetNamespace = "http://www.valencia.es/services/nieDomain/UnidadesOrganizativas/v20", partName = "response")
    @WebMethod(action = "http://www.valencia.es/services/nieDomain/UnidadesOrganizativas/v10/addOrUpdateUnidad")
    public es.valencia.services.niedomain.unidadesorganizativas.UnidadResponseTypeV20 addOrUpdateUnidad(
        @WebParam(partName = "request", name = "AddOrUpdateUnidadRequest", targetNamespace = "http://www.valencia.es/services/nieDomain/UnidadesOrganizativas/v20")
        es.valencia.services.niedomain.unidadesorganizativas.AddOrUpdateUnidadRequestTypeV20 request
    ) throws UnidadPreconditionFault;
}
