-- SUSTITUIR LOS TABLESPACES (TS_DATOS, TS_INDICES) POR LOS CORRECTOS 

  CREATE TABLE COCHES 
   (	ID NUMBER(19,0), 
	COLOR VARCHAR2(10 CHAR), 
	MATRICULA VARCHAR2(10 CHAR), 
	MODELO VARCHAR2(250 CHAR), 
	USUARIO_RESERVA VARCHAR2(20 CHAR)
   ) TABLESPACE TS_DATOS
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;



CREATE TABLE MENUITEMS
(
  COD_ITEM                 NUMBER(19) CONSTRAINT MENUITEMS_COD_ITEM_NN NOT NULL,
  ES_DIALOGO               NUMBER(1),
  TXT_IMAGEPATH            VARCHAR2(255 CHAR),
  ES_INTERNA               NUMBER(1),
  TXT_LANGUAGE             VARCHAR2(255 CHAR),
  TXT_PATH                 VARCHAR2(255 CHAR),
  COD_PARENTID             NUMBER(19),
  TXT_SECURITY_EXPRESSION  VARCHAR2(255 CHAR),
  TXT_TITLE                VARCHAR2(255 CHAR),
  NUM_WEIGHT               NUMBER(10)
)
TABLESPACE TS_DATOS
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE MENUITEMS IS 'Tabla con las entradas de menú de la aplicación.';

COMMENT ON COLUMN MENUITEMS.COD_ITEM IS 'Identificador de la entrada de menú.';

COMMENT ON COLUMN MENUITEMS.ES_DIALOGO IS 'Indica si la entrada de menú abre un dialogo o una página. 0- Página, 1 - Diálogo.';

COMMENT ON COLUMN MENUITEMS.TXT_IMAGEPATH IS 'Syleclass de la imagen/icono utilizado en la entrada de menú.';

COMMENT ON COLUMN MENUITEMS.ES_INTERNA IS 'Indica si la url de la entrada de menú es relativa al contexto de la aplicación o es una url externa.';

COMMENT ON COLUMN MENUITEMS.TXT_LANGUAGE IS 'Idioma en el que se utilizará dicha entrada de menú.';

COMMENT ON COLUMN MENUITEMS.TXT_PATH IS 'Url a la que apunta.';

COMMENT ON COLUMN MENUITEMS.COD_PARENTID IS 'Padre de la entrada de menú (menú anidado).';

COMMENT ON COLUMN MENUITEMS.TXT_SECURITY_EXPRESSION IS 'Expresión de seguridad Spring utilizada para mostrar o no la entrada de menú.';

COMMENT ON COLUMN MENUITEMS.TXT_TITLE IS 'Texto de la entrada de menú.';

COMMENT ON COLUMN MENUITEMS.NUM_WEIGHT IS 'Peso. Utilizado para ordenar las entradas de menú.';



CREATE TABLE REVENTITY
(
  ID         NUMBER(10) CONSTRAINT REVENTITY_ID_NN NOT NULL,
  TIMESTAMP  NUMBER(19) CONSTRAINT REVENTITY_TIMESTAMP_NN NOT NULL,
  USERNAME   VARCHAR2(255 CHAR)
)
TABLESPACE TS_DATOS
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE REVENTITY IS 'Guarda el número de versión, usuario y timestamp de las modificaciones realizadas sobre las tablas auditadas por Hibernate Envers.';

COMMENT ON COLUMN REVENTITY.ID IS 'Identificador de versión.';

COMMENT ON COLUMN REVENTITY.TIMESTAMP IS 'Timestamp de la versión.';

COMMENT ON COLUMN REVENTITY.USERNAME IS 'Nombre de usuario que ha provocado la modificación.';



CREATE TABLE SUSTITUTO_AUD
(
  REV           NUMBER(10) CONSTRAINT SUSTITUTO_AUD_REV_NN NOT NULL,
  REVTYPE       NUMBER(3) CONSTRAINT SUSTITUTO_AUD_REVTYPE_NN NOT NULL,
  SU_UO_ID      NUMBER(19) CONSTRAINT SUSTITUTO_AUD_SU_UO_ID_NN NOT NULL,
  SETORDINAL    NUMBER(10) CONSTRAINT SUSTITUTO_AUD_SETORDINAL_NN NOT NULL,
  REVEND        NUMBER(10),
  REVEND_TSTMP  TIMESTAMP(6),
  SU_APELLIDO2  VARCHAR2(60 CHAR),
  SU_NOMBRE     VARCHAR2(60 CHAR),
  SU_CARGO_VAL  VARCHAR2(100 CHAR),
  SU_NIF        VARCHAR2(10 CHAR),
  SU_USUARIO    VARCHAR2(20 CHAR),
  SU_APELLIDO1  VARCHAR2(60 CHAR),
  SU_CARGO_CAS  VARCHAR2(100 CHAR)
)
TABLESPACE TS_DATOS
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE SUSTITUTO_AUD IS 'Tabla que contiene los usuarios que pueden ejercer de sustituto en cada unidado organizativa.';

COMMENT ON COLUMN SUSTITUTO_AUD.REV IS 'Identificador de la revisión. Guarda el número de revisión en el que se realiza la modificación.';

COMMENT ON COLUMN SUSTITUTO_AUD.REVTYPE IS 'Tipo de modificación. 0 - Insert, 1 - Update y 2 - Delete.';

COMMENT ON COLUMN SUSTITUTO_AUD.REVEND IS 'Identificador de la siguiente modificación para ese identificador. En caso de ser la última modificación, este campo está a NULL.';

COMMENT ON COLUMN SUSTITUTO_AUD.REVEND_TSTMP IS 'TimeStamp con la fecha del final de la revisión. Es la fecha en la que se generó REVEND';



CREATE TABLE UNIDAD_ORGANIZATIVA
(
  UO_ID                         NUMBER(19) CONSTRAINT UNIDAD_ORG_UO_ID_NN NOT NULL,
  UO_AMBITO_RESTRING_ENVIO      NUMBER(1) CONSTRAINT UNIDAD_ORG_UO_AMBIT_ENVIO_NN NOT NULL,
  UO_AMBITO_RESTRING_RECEPCION  NUMBER(1) CONSTRAINT UNIDAD_ORG_UO_AMBIT_RECEP_NN NOT NULL,
  UO_CODIGO_BDO                 NUMBER(19),
  UO_CODIGO_INVARIABLE          VARCHAR2(6 CHAR),
  UO_CODIGO_ORGANICO_EXTERNO    VARCHAR2(30 CHAR),
  UO_CODIGO_ORGANICO_INTERNO    VARCHAR2(30 CHAR),
  UO_EMISORA_NI                 NUMBER(1) CONSTRAINT UNIDAD_ORG_UO_EMISORA_NI_NN NOT NULL,
  FORCE_UPDATE                  NUMBER(10),
  UO_NOMBRE_UNIDAD_CAS          VARCHAR2(120 CHAR),
  UO_NOMBRE_UNIDAD_VAL          VARCHAR2(120 CHAR),
  OCC_VERSION                   NUMBER(10),
  UO_PRIMER_NIVEL               NUMBER(1) CONSTRAINT UNIDAD_ORG_UO_PRIMER_NIVEL_NN NOT NULL,
  UO_RECEPTORA_NI               NUMBER(1) CONSTRAINT UNIDAD_ORG_UO_RECEPTORA_NI_NN NOT NULL,
  UO_RESPONSABLE_APELLIDO1      VARCHAR2(60 CHAR),
  UO_RESPONSABLE_APELLIDO2      VARCHAR2(60 CHAR),
  UO_RESPONSABLE_NIF            VARCHAR2(10 CHAR),
  UO_RESPONSABLE_NOMBRE         VARCHAR2(60 CHAR),
  UO_RESPONSABLE_CARGO_CAS      VARCHAR2(100 CHAR),
  UO_RESPONSABLE_CARGO_VAL      VARCHAR2(100 CHAR),
  UO_RESPONSABLE_USUARIO        VARCHAR2(20 CHAR),
  UO_UID                        VARCHAR2(10 CHAR),
  UO_VIGENTE                    NUMBER(1) CONSTRAINT UNIDAD_ORG_UO_VIGENTE_NN NOT NULL,
  UO_REDIRECCION_BUZON          NUMBER(19),
  UO_UNIDAD_PADRE               NUMBER(19)
)
TABLESPACE TS_DATOS
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN UNIDAD_ORGANIZATIVA.UO_ID IS 'Clave primaria interna generada por Hibernate (kid).';

COMMENT ON COLUMN UNIDAD_ORGANIZATIVA.UO_AMBITO_RESTRING_ENVIO IS 'Indica si la unidad (siendo de segundo nivel) solo puede enviar comunicaciones dentro de su Ã¡mbito de primer nivel. Valores:  1- SÃ³lo pueden enviar dentro de su Ã¡mbito de primer nivel. 0 - Puede enviar fuera de su Ã¡mbito de primer nivel.';

COMMENT ON COLUMN UNIDAD_ORGANIZATIVA.UO_AMBITO_RESTRING_RECEPCION IS 'Indica si la unidad (siendo de segundo nivel) solo es visible dentro de su Ã¡mbito de primer nivel. Valores:  1- La unidad solo es visible para la unidades de su Ã¡mbito de primer nivel. 0 - La unidad es visible para todas las unidades.';

COMMENT ON COLUMN UNIDAD_ORGANIZATIVA.UO_CODIGO_BDO IS 'Código BDO. (Dato obtenido de BDO)';

COMMENT ON COLUMN UNIDAD_ORGANIZATIVA.UO_CODIGO_INVARIABLE IS 'Código Invariable. (Dato obtenido de BDO)';

COMMENT ON COLUMN UNIDAD_ORGANIZATIVA.UO_CODIGO_ORGANICO_EXTERNO IS 'Código organico exerno. (Dato obtenido de BDO)';

COMMENT ON COLUMN UNIDAD_ORGANIZATIVA.UO_CODIGO_ORGANICO_INTERNO IS 'Código orgánico interno. (Dato obtenido de BDO)';

COMMENT ON COLUMN UNIDAD_ORGANIZATIVA.UO_EMISORA_NI IS 'Indica si la unidad puede emitir notas interiores. 0 - No , 1 - Sí.';

COMMENT ON COLUMN UNIDAD_ORGANIZATIVA.FORCE_UPDATE IS 'Campo utilizado para forzar la actualización del regstro durante el proceso de de carga de unidades organizativas. ';

COMMENT ON COLUMN UNIDAD_ORGANIZATIVA.UO_NOMBRE_UNIDAD_CAS IS 'Nombre de la unidad en Castellano. (Dato obtenido de BDO)';

COMMENT ON COLUMN UNIDAD_ORGANIZATIVA.UO_NOMBRE_UNIDAD_VAL IS 'Nombre de la unidad en Valenciano. (Dato obtenido de BDO)';

COMMENT ON COLUMN UNIDAD_ORGANIZATIVA.OCC_VERSION IS 'Número de versión utilizado por hibernate para el OCC (Control de concurrencia optimista).';

COMMENT ON COLUMN UNIDAD_ORGANIZATIVA.UO_PRIMER_NIVEL IS 'Indica si la unidad es de primer nivel. 0 - No , 1 - Sí.  (Dato obtenido de BDO)';

COMMENT ON COLUMN UNIDAD_ORGANIZATIVA.UO_RECEPTORA_NI IS 'Indica si la unidad puede recibir notas interiores. 0- No , 1 - Sí.';

COMMENT ON COLUMN UNIDAD_ORGANIZATIVA.UO_RESPONSABLE_APELLIDO1 IS 'Primer apellido del responsable de la unidad.  (Dato obtenido de BDO)';

COMMENT ON COLUMN UNIDAD_ORGANIZATIVA.UO_RESPONSABLE_APELLIDO2 IS 'Segundo apellido del responsable de la unidad.  (Dato obtenido de BDO)';

COMMENT ON COLUMN UNIDAD_ORGANIZATIVA.UO_RESPONSABLE_NIF IS 'NIF del responsable de la unidad.  (Dato obtenido de BDO)';

COMMENT ON COLUMN UNIDAD_ORGANIZATIVA.UO_RESPONSABLE_NOMBRE IS 'Nombre del responsable de la unidad.  (Dato obtenido de BDO)';

COMMENT ON COLUMN UNIDAD_ORGANIZATIVA.UO_RESPONSABLE_CARGO_CAS IS 'Cargo que ocupa el responsable de la unidad (en Castellano).  (Dato obtenido de BDO)';

COMMENT ON COLUMN UNIDAD_ORGANIZATIVA.UO_RESPONSABLE_CARGO_VAL IS 'Cargo que ocupa el responsable de la unidad (en Valenciano).  (Dato obtenido de BDO)';

COMMENT ON COLUMN UNIDAD_ORGANIZATIVA.UO_RESPONSABLE_USUARIO IS 'Nombre de usuario del responsable de la unidad.   (Dato obtenido de BDO)';

COMMENT ON COLUMN UNIDAD_ORGANIZATIVA.UO_UID IS 'Identificador de dominio (NIE) de la Unidad Organizativa. Ha sido creado para NIE porque BDO no dispone de un campo que se pueda calificar de "identificador" para las Unidades Organizativas. Este campo será igual al código invariable si existe, o en su defecto será igual al código interno de BDO.';

COMMENT ON COLUMN UNIDAD_ORGANIZATIVA.UO_VIGENTE IS 'Indica si la unidad sigue vigente o no. (Dato obtenido de BDO)';

COMMENT ON COLUMN UNIDAD_ORGANIZATIVA.UO_REDIRECCION_BUZON IS 'ID de la unidad organizativa a la que se redireccionarÃ¡n las notas interiores ';

COMMENT ON COLUMN UNIDAD_ORGANIZATIVA.UO_UNIDAD_PADRE IS 'UO_ID de la unidad padre. (Dato obtenido de BDO)';



CREATE TABLE UNIDAD_ORGANIZATIVA_AUD
(
  UO_ID                         NUMBER(19) CONSTRAINT UNIDAD_ORG_AUD_UO_ID_NN NOT NULL,
  REV                           NUMBER(10) CONSTRAINT UNIDAD_ORG_AUD_REV_NN NOT NULL,
  REVTYPE                       NUMBER(3),
  REVEND                        NUMBER(10),
  REVEND_TSTMP                  TIMESTAMP(6),
  UO_AMBITO_RESTRING_ENVIO      NUMBER(1),
  UO_AMBITO_RESTRING_RECEPCION  NUMBER(1),
  UO_CODIGO_BDO                 NUMBER(19),
  UO_CODIGO_INVARIABLE          VARCHAR2(6 CHAR),
  UO_CODIGO_ORGANICO_EXTERNO    VARCHAR2(30 CHAR),
  UO_CODIGO_ORGANICO_INTERNO    VARCHAR2(30 CHAR),
  UO_EMISORA_NI                 NUMBER(1),
  UO_NOMBRE_UNIDAD_CAS          VARCHAR2(120 CHAR),
  UO_NOMBRE_UNIDAD_VAL          VARCHAR2(120 CHAR),
  UO_PRIMER_NIVEL               NUMBER(1),
  UO_RECEPTORA_NI               NUMBER(1),
  UO_RESPONSABLE_APELLIDO1      VARCHAR2(60 CHAR),
  UO_RESPONSABLE_APELLIDO2      VARCHAR2(60 CHAR),
  UO_RESPONSABLE_NIF            VARCHAR2(10 CHAR),
  UO_RESPONSABLE_NOMBRE         VARCHAR2(60 CHAR),
  UO_RESPONSABLE_CARGO_CAS      VARCHAR2(100 CHAR),
  UO_RESPONSABLE_CARGO_VAL      VARCHAR2(100 CHAR),
  UO_RESPONSABLE_USUARIO        VARCHAR2(20 CHAR),
  UO_UID                        VARCHAR2(10 CHAR),
  UO_VIGENTE                    NUMBER(1),
  UO_REDIRECCION_BUZON          NUMBER(19),
  UO_UNIDAD_PADRE               NUMBER(19)
)
TABLESPACE TS_DATOS
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE UNIDAD_ORGANIZATIVA_AUD IS 'Tabla de auditoria de unidades organizativas. Audita las modificaciones realizadas en  UNIDAD_ORGANIZATIVA.';

COMMENT ON COLUMN UNIDAD_ORGANIZATIVA_AUD.REV IS 'Identificador de la revisión. Guarda el número de revisión en el que se realiza la modificación.';

COMMENT ON COLUMN UNIDAD_ORGANIZATIVA_AUD.REVTYPE IS 'Tipo de modificación. 0 - Insert, 1 - Update y 2 - Delete.';

COMMENT ON COLUMN UNIDAD_ORGANIZATIVA_AUD.REVEND IS 'Identificador de la siguiente modificación para ese identificador. En caso de ser la última modificación, este campo está a NULL.';

COMMENT ON COLUMN UNIDAD_ORGANIZATIVA_AUD.REVEND_TSTMP IS 'TimeStamp con la fecha del final de la revisión. Es la fecha en la que se generó REVEND';

COMMENT ON COLUMN UNIDAD_ORGANIZATIVA_AUD.UO_AMBITO_RESTRING_ENVIO IS 'Indica si la unidad (siendo de segundo nivel) solo puede enviar comunicaciones dentro de su Ã¡mbito de primer nivel. Valores:  1- SÃ³lo pueden enviar dentro de su Ã¡mbito de primer nivel. 0 - Puede enviar fuera de su Ã¡mbito de primer nivel.';

COMMENT ON COLUMN UNIDAD_ORGANIZATIVA_AUD.UO_AMBITO_RESTRING_RECEPCION IS 'Indica si la unidad (siendo de segundo nivel) solo es visible dentro de su Ã¡mbito de primer nivel. Valores:  1- La unidad solo es visible para la unidades de su Ã¡mbito de primer nivel. 0 - La unidad es visible para todas las unidades.';



CREATE TABLE LISTA_DESTINO
(
  LD_LISTA_ID            NUMBER(19) CONSTRAINT LISTA_DESTINO_LD_LISTA_ID_NN NOT NULL,
  LD_DESCRIPCION         VARCHAR2(255 CHAR),
  LD_FECHA_CREACION      TIMESTAMP(6),
  LD_FECHA_MODIFICACION  TIMESTAMP(6),
  LD_NOMBRE_CAS          VARCHAR2(150 CHAR) CONSTRAINT LISTA_DESTINO_LD_NOMBRE_CAS_NN NOT NULL,
  LD_NOMBRE_VAL          VARCHAR2(150 CHAR) CONSTRAINT LISTA_DESTINO_LD_NOMBRE_VAL_NN NOT NULL,
  OCC_VERSION            NUMBER(10),
  LD_UO_ID               NUMBER(19)
)
TABLESPACE TS_DATOS
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE LISTA_DESTINO IS 'Tabla de Listas de destino.';

COMMENT ON COLUMN LISTA_DESTINO.LD_LISTA_ID IS 'Identificador (kid) de la lista generado por hibernate.';

COMMENT ON COLUMN LISTA_DESTINO.LD_DESCRIPCION IS 'Descripción de la lista destino.';

COMMENT ON COLUMN LISTA_DESTINO.LD_FECHA_CREACION IS 'Columna de auditoria. Fecha de creación de la lista.';

COMMENT ON COLUMN LISTA_DESTINO.LD_FECHA_MODIFICACION IS 'Columna de auditoria. Fecha de modificación de la lista.';

COMMENT ON COLUMN LISTA_DESTINO.LD_NOMBRE_CAS IS 'Nombre, en castellano, de la lista destino.';

COMMENT ON COLUMN LISTA_DESTINO.LD_NOMBRE_VAL IS 'Nombre, en valenciano, de la lista destino.';

COMMENT ON COLUMN LISTA_DESTINO.OCC_VERSION IS 'Número de versión utilizado por hibernate para el OCC (Control de concurrencia optimista).';

COMMENT ON COLUMN LISTA_DESTINO.LD_UO_ID IS 'Identificador de la unidad organizativa propietaria de la lista destino. Si este campo se encuentra a null es una lista global que puede ser usada por todas las unidades.';



CREATE TABLE LISTA_DESTINO_UNIDADES
(
  LDU_LISTA_ID  NUMBER(19) CONSTRAINT LISTA_DEST_UO_LDU_LISTA_ID_NN NOT NULL,
  LDU_UO_ID     NUMBER(19) CONSTRAINT LISTA_DEST_UO_LDU_UO_ID_NN NOT NULL
)
TABLESPACE TS_DATOS
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON TABLE LISTA_DESTINO_UNIDADES IS 'Unidades Organizativas que pertenecen a una lista de destino.';

COMMENT ON COLUMN LISTA_DESTINO_UNIDADES.LDU_LISTA_ID IS 'Identificador (kid) de la lista destino.';

COMMENT ON COLUMN LISTA_DESTINO_UNIDADES.LDU_UO_ID IS 'Identificador (kid) de la unidad organizativa.';



CREATE TABLE SUSTITUTO
(
  SU_UO_ID      NUMBER(19) CONSTRAINT SUSTITUTO_SU_UO_ID_NN NOT NULL,
  SU_APELLIDO1  VARCHAR2(60 CHAR),
  SU_APELLIDO2  VARCHAR2(60 CHAR),
  SU_NIF        VARCHAR2(10 CHAR),
  SU_NOMBRE     VARCHAR2(60 CHAR),
  SU_CARGO_CAS  VARCHAR2(100 CHAR),
  SU_CARGO_VAL  VARCHAR2(100 CHAR),
  SU_USUARIO    VARCHAR2(20 CHAR)
)
TABLESPACE TS_DATOS
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN SUSTITUTO.SU_APELLIDO1 IS 'Primer apellido del sustituto de la unidad. ';

COMMENT ON COLUMN SUSTITUTO.SU_APELLIDO2 IS 'Segundo apellido del sustituto de la unidad.';

COMMENT ON COLUMN SUSTITUTO.SU_NIF IS 'NIF del sustituto de la unidad.';

COMMENT ON COLUMN SUSTITUTO.SU_NOMBRE IS 'Nombre del sustituto de la unidad.';

COMMENT ON COLUMN SUSTITUTO.SU_CARGO_CAS IS 'Cargo que ocupa el sustituto de la unidad (en Castellano).';

COMMENT ON COLUMN SUSTITUTO.SU_CARGO_VAL IS 'Cargo que ocupa el sustituto de la unidad (en Valenciano).';

COMMENT ON COLUMN SUSTITUTO.SU_USUARIO IS 'Nombre de usuario del responsable de la unidad.';





CREATE UNIQUE INDEX COCHES_PK ON COCHES 
(ID)
LOGGING
TABLESPACE TS_INDICES
NOPARALLEL;


CREATE UNIQUE INDEX COCHES_MATRICULA_UK ON COCHES
(MATRICULA)
LOGGING
TABLESPACE TS_INDICES
NOPARALLEL;


CREATE UNIQUE INDEX MENUITEMS_PK ON MENUITEMS
(COD_ITEM)
LOGGING
TABLESPACE TS_INDICES
NOPARALLEL;


CREATE UNIQUE INDEX REVENTITY_PK ON REVENTITY
(ID)
LOGGING
TABLESPACE TS_INDICES
NOPARALLEL;


CREATE UNIQUE INDEX SUSTITUTO_AUD_PK ON SUSTITUTO_AUD
(REV, REVTYPE, SU_UO_ID, SETORDINAL)
LOGGING
TABLESPACE TS_INDICES
NOPARALLEL;


CREATE UNIQUE INDEX UNIDAD_ORGANIZATIVA_PK ON UNIDAD_ORGANIZATIVA
(UO_ID)
LOGGING
TABLESPACE TS_INDICES
NOPARALLEL;


CREATE UNIQUE INDEX UNIDAD_ORG_UO_UID_UK ON UNIDAD_ORGANIZATIVA
(UO_UID)
LOGGING
TABLESPACE TS_INDICES
NOPARALLEL;



CREATE UNIQUE INDEX LISTA_DESTINO_PK ON LISTA_DESTINO
(LD_LISTA_ID)
LOGGING
TABLESPACE TS_INDICES
NOPARALLEL;


CREATE UNIQUE INDEX LISTA_DESTINO_UNIDADES_PK ON LISTA_DESTINO_UNIDADES
(LDU_LISTA_ID, LDU_UO_ID)
LOGGING
TABLESPACE TS_INDICES
NOPARALLEL;


CREATE UNIQUE INDEX LISTA_DEST__NOM_CAS__UO_ID_UK ON LISTA_DESTINO
(LD_NOMBRE_CAS, LD_UO_ID)
LOGGING
TABLESPACE TS_INDICES
NOPARALLEL;


ALTER TABLE MENUITEMS ADD (
  CONSTRAINT MENUITEMS_PK
  PRIMARY KEY
  (COD_ITEM)
  USING INDEX MENUITEMS_PK);

ALTER TABLE REVENTITY ADD (
  CONSTRAINT REVENTITY_PK
  PRIMARY KEY
  (ID)
  USING INDEX REVENTITY_PK);

ALTER TABLE SUSTITUTO_AUD ADD (
  CONSTRAINT SUSTITUTO_AUD_PK
  PRIMARY KEY
  (REV, REVTYPE, SU_UO_ID, SETORDINAL)
  USING INDEX SUSTITUTO_AUD_PK);

ALTER TABLE UNIDAD_ORGANIZATIVA ADD (
  CONSTRAINT UNIDAD_ORGANIZATIVA_PK
  PRIMARY KEY
  (UO_ID)
  USING INDEX UNIDAD_ORGANIZATIVA_PK,
  CONSTRAINT UNIDAD_ORG_UO_UID_UK
  UNIQUE (UO_UID)
  USING INDEX UNIDAD_ORG_UO_UID_UK);

ALTER TABLE UNIDAD_ORGANIZATIVA_AUD ADD (
  CONSTRAINT UNIDAD_ORGANIZATIVA_AUD_PK
  PRIMARY KEY
  (UO_ID, REV)
  USING INDEX
    TABLESPACE TS_INDICES);

ALTER TABLE LISTA_DESTINO ADD (
  CONSTRAINT LISTA_DESTINO_PK
  PRIMARY KEY
  (LD_LISTA_ID)
  USING INDEX LISTA_DESTINO_PK,
  CONSTRAINT LISTA_DEST__NOM_CAS__UO_ID_UK
  UNIQUE (LD_NOMBRE_CAS, LD_UO_ID)
  USING INDEX LISTA_DEST__NOM_CAS__UO_ID_UK);

ALTER TABLE LISTA_DESTINO_UNIDADES ADD (
  CONSTRAINT LISTA_DESTINO_UNIDADES_PK
  PRIMARY KEY
  (LDU_LISTA_ID, LDU_UO_ID)
  USING INDEX LISTA_DESTINO_UNIDADES_PK);

ALTER TABLE SUSTITUTO_AUD ADD (
  CONSTRAINT SUSTITUTO_AUD_REVENTITY_END_FK 
  FOREIGN KEY (REVEND) 
  REFERENCES REVENTITY (ID),
  CONSTRAINT SUSTITUTO_AUD_REVENTITY_REV_FK 
  FOREIGN KEY (REV) 
  REFERENCES REVENTITY (ID));

ALTER TABLE UNIDAD_ORGANIZATIVA ADD (
  CONSTRAINT UNIDAD_ORG_PADRE_FK 
  FOREIGN KEY (UO_UNIDAD_PADRE) 
  REFERENCES UNIDAD_ORGANIZATIVA (UO_ID),
  CONSTRAINT UNIDAD_ORG_UNIDAD_REDIREC_FK 
  FOREIGN KEY (UO_REDIRECCION_BUZON) 
  REFERENCES UNIDAD_ORGANIZATIVA (UO_ID));

ALTER TABLE UNIDAD_ORGANIZATIVA_AUD ADD (
  CONSTRAINT UNIDAD_ORGA_AUD_REVENT_END_FK 
  FOREIGN KEY (REVEND) 
  REFERENCES REVENTITY (ID),
  CONSTRAINT UNIDAD_ORG_AUD_REVENT_REV_FK 
  FOREIGN KEY (REV) 
  REFERENCES REVENTITY (ID));

ALTER TABLE LISTA_DESTINO ADD (
  CONSTRAINT LISTA_DEST_UNIDAD_ORG_FK 
  FOREIGN KEY (LD_UO_ID) 
  REFERENCES UNIDAD_ORGANIZATIVA (UO_ID));

ALTER TABLE LISTA_DESTINO_UNIDADES ADD (
  CONSTRAINT LISTA_DEST_UOS_UNIDAD_ORG_FK 
  FOREIGN KEY (LDU_UO_ID) 
  REFERENCES UNIDAD_ORGANIZATIVA (UO_ID),
  CONSTRAINT LISTA_DEST_UO_LISTA_DESTINO_FK 
  FOREIGN KEY (LDU_LISTA_ID) 
  REFERENCES LISTA_DESTINO (LD_LISTA_ID));

ALTER TABLE SUSTITUTO ADD (
  CONSTRAINT SUSTITUTO_UNIDAD_ORG_FK 
  FOREIGN KEY (SU_UO_ID) 
  REFERENCES UNIDAD_ORGANIZATIVA (UO_ID));


  
  ALTER TABLE COCHES ADD (
  CONSTRAINT COCHES_PK
  PRIMARY KEY
  (ID)
  USING INDEX COCHES_PK);
  
  ALTER TABLE COCHES ADD (
  CONSTRAINT COCHES_MATRICULA_UK
  UNIQUE (MATRICULA)
  USING INDEX COCHES_MATRICULA_UK);
  
  ALTER TABLE COCHES MODIFY (ID CONSTRAINT COCHES_ID_NN NOT NULL );
  
  
  CREATE SEQUENCE HIBERNATE_SEQUENCE
  START WITH 101
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


  CREATE SEQUENCE LISTADEST_SEQUENCE
  START WITH 81
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

CREATE SEQUENCE  COCHE_SEQUENCE
  START WITH 0
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

CREATE SEQUENCE UNIORG_SEQUENCE
  START WITH 81
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

CREATE SEQUENCE  CONT_MENUITEMS
  START WITH 10
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;